version: '3.9'
services:

  nginx_server:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./upstreams.conf:/etc/nginx/conf.d/upstreams.conf
      - ./ssl:/var/ssl
    restart: unless-stopped
    #command: ["sysctl", "-w", "fs.file-max=1048576"]
    ulimits:
       nproc: 1048576
       nofile:
         soft: 500000
         hard: 1048576
    tty: true
    ports:
      - "8071:8071"
      #- "80:80"
      #- "443:443"
    networks:
     web:
       ipv4_address: 172.16.238.8
  


  node_app:
    build:
      context: .
      dockerfile: ./dockerNodeApp
    command: ["node", "ws", "9000"]
    deploy:
      mode: replicated
      replicas: 3
    networks:
        - web
  


networks:
  web:
    external: true