version: '3.9'
services:

  nginx_server:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./upstreams.conf:/etc/nginx/conf.d/upstreams.conf
    restart: unless-stopped
    tty: true
    ports:
      - "82:80"
    #  - "443:443"
    networks:
     web:
       ipv4_address: 172.16.238.7

  node_app:
    build:
      context: .
      dockerfile: ./dockerNodeApp
    container_name: node_app
    networks:
     web:
       ipv4_address: 172.16.238.8
  


networks:
  web:
    external: true