version: '3.9'
services:

  nginx_server:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./upstreams.conf:/etc/nginx/conf.d/upstreams.conf
    restart: unless-stopped
    #command: ["sysctl", "-w", "fs.file-max=1048576"]
    ulimits:
       nproc: 500000
    tty: true
    ports:
      - "8071:8071"
      #- "80:80"
      #- "443:443"
    networks:
     web:
       ipv4_address: 172.16.238.7
  


  node_app:
    build:
      context: .
      dockerfile: ./dockerNodeApp
    container_name: node_app
    command: ["node", "wsd", "9000"]
    deploy:
      mode: replicated
      replicas: 3
    networks:
        - websocket
  


networks:
  web:
    external: true
  websocket:
    driver: bridge
    name: websocket
    ipam:
      driver: default
      config:
        - subnet: 172.16.237.0/24